In [1]:
people = [{'name': 'Alice', 'age': 30}, {'name': 'Bob', 'age': 20}]
sorted_people = sorted(people, key=lambda x: x['age'])
print(sorted_people)

[{'name': 'Bob', 'age': 20}, {'name': 'Alice', 'age': 30}]


In [ ]:
🔁 Lambda with map(), filter(), sorted()

In [5]:
nums = [1,2,4,6]
square= list(map(lambda x:x**2,nums))
print(square)

[1, 4, 16, 36]


In [7]:
even_nums = list(filter(lambda x: x % 2 == 0, nums))
print(even_nums)  # [2, 4]

# sorted() with lambda
people = [{'name': 'Alice', 'age': 30}, {'name': 'Bob', 'age': 20}]
sorted_people = sorted(people, key=lambda x: x['age'])
print(sorted_people)

[2, 4, 6]
[{'name': 'Bob', 'age': 20}, {'name': 'Alice', 'age': 30}]


In [ ]:
📚 List Comprehensions in Python

| Task                    | List Comprehension Example               |
| ----------------------- | ---------------------------------------- |
| Squares                 | `[x**2 for x in range(10)]`              |
| Filter strings          | `[s for s in names if len(s) > 3]`       |
| Flatten list of lists   | `[num for sub in nested for num in sub]` |
| Convert to uppercase    | `[char.upper() for char in "hello"]`     |
| Remove duplicates (set) | `list(set([1, 2, 2, 3]))`                |


In [8]:
square = [x**2 for x in range(5)]
print(square)

[0, 1, 4, 9, 16]


In [28]:
import numpy as np

arrayNum= np.array([[1,2,3],[4,5,6]]) #2d
arrayNum1= np.array([
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
]) #3d
print(arrayNum)
print(arrayNum1.shape)  # Dimensions (rows, cols)    
print(arrayNum1.ndim)      # Number of dimensions
arr.dtype      # Data type of elements
arr.size       # Total number of elements
arr.itemsize   # Size (in bytes) of each item


[[1 2 3]
 [4 5 6]]
(2, 4, 3)
3


8

In [ ]:
🧮 NumPy Basics: Arrays, Indexing, Broadcasting & More

In [ ]:
Creating Arrays

In [20]:
# Arrays filled with zeros or ones
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))

print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:

# Array with a range
arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

# Linearly spaced array
lin = np.linspace(0, 1, 5)  # [0. , 0.25, 0.5 , 0.75, 1. ]

# Identity matrix
eye = np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
Indexing & Slicing

In [ ]:
a = np.array([10, 20, 30, 40, 50])

# Indexing
print(a[0])        # 10

# Slicing
print(a[1:4])      # [20, 30, 40]

# 2D array indexing
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[0, 2])     # 3
print(b[:, 1])     # [2, 5]


In [ ]:
 Array Operations

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print(a + b)       # [5 7 9]
print(a * b)       # [4 10 18]

# Scalar operations
print(a * 2)       # [2 4 6]

# Universal Functions (ufuncs)
np.sqrt(a)
np.sin(a)
np.log(a)


In [ ]:
Broadcasting

In [ ]:
Reshape and Flatten

In [ ]:
a = np.arange(6)         # [0 1 2 3 4 5]
b = a.reshape(2, 3)      # 2 rows, 3 columns

c = b.flatten()          # Back to 1D


In [ ]:
🧼 8. Useful Functions

In [ ]:
np.sum(arr)           # Sum of elements
np.mean(arr)          # Average
np.std(arr)           # Standard deviation
np.max(arr), np.min(arr)
np.argmax(arr)        # Index of max value
np.cumsum(arr)        # Cumulative sum

In [ ]:
 Boolean Indexing & Filtering

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a[a > 3])     # [4 5]


| Feature      | Function / Syntax                |
| ------------ | -------------------------------- |
| Create array | `np.array()`, `np.zeros()`, etc. |
| Index/slice  | `a[1:3]`, `a[0, 2]`              |
| Operations   | `+`, `-`, `*`, `/`, `np.sqrt()`  |
| Reshape      | `a.reshape()`, `a.flatten()`     |
| Broadcasting | Auto shape-matching              |
| Statistics   | `np.mean()`, `np.sum()`, etc.    |
| Filtering    | `a[a > 0]`                       |
